### ISSUE TITLE
KeyError: 'leiden' when setting the parameter clust_key

### ISSUE THREAD

**Issue by andreassteffen** [deweylab/CellO#14]
__reproduce__
use cello.scanpy_cello with clust_key set to existing obs column that is not 'leiden'

__expected behavior__
cello would use the set clustering key

__observed behaviour__
cello crashes with: KeyError: 'leiden'

__identified bug__
cello.py line 429 
`ad_clust = _combine_by_cluster(ad)`

should be

`ad_clust = _combine_by_cluster(ad, clust_key)`

**Comment by mbernste** [comment]
Hi, I am the main maintainer of CellO. While I hope to keep maintaining CellO, I recently changed positions and no longer work in the lab where I developed CellO. Bug-fixes and improvements to CellO may not be as timely as I would like them to be. I appreciate your understanding.

**Comment by mbernste** [comment]
In regard to this issues, it was recently fixed (https://github.com/deweylab/CellO/pull/16). Please let me know if you continue to experience problems

**Comment by ggayq** [comment]
thanks!
