### ISSUE TITLE
Could you provide a ftp link to the CellO resources? 

### ISSUE THREAD

**Issue by brainfo** [deweylab/CellO#17]
Hi,
I wanna know more about the source you use to train your data to make a predecision on how to use this tool.
Maybe I don't find a proper citation to CellO, so I cannot know before I implement your tool. Could I have a look on the source (and/or process) you used to train the model?

Thanks!

**Comment by mbernste** [comment]
Hi, are you looking for the publication where we describe the methodology behind CellO? That can be found here: https://www.sciencedirect.com/science/article/pii/S258900422031110X
