### ISSUE TITLE
"else" is missing

### ISSUE THREAD

**Issue by ramonvidal** [deweylab/CellO#2]
I have failed multiple times until I noticed I was using "csv" instead of "CSV" as parameter. An "else" here would be helpful for warn users about typos in parameters. 

https://github.com/deweylab/CellO/blob/79db145ed6d02cdbf3f694719d30fd61b3fd863d/utils/load_expression_matrix.py#L20

**Comment by mbernste** [comment]
Thank you for this suggestion. I have updated this function to provide an error message when the user specifies an incorrect option.
