### ISSUE TITLE
FileNotFoundError: CellO/resources/trained_models/clr.10x_genes_thresholds.tsv' does not exist

### ISSUE THREAD

**Issue by shinthor** [deweylab/CellO#3]
This error occurs when running CellO using CLR and using a 10x input. Running download_resources.sh downloads a file named cdc.10x_genes_thresholds.tsv. This should be renamed to clr.10x_genes_thresholds.

**Comment by mbernste** [comment]
Hi, thank you very much for alerting us to this. I believe this was fixed in a later update to CellO's resources files. If you download the new version the file should have the appropriate name.

Please let us know if you have any other issues.
