### ISSUE TITLE
InvalidIndexError: Reindexing only valid with uniquely valued Index objects

### ISSUE THREAD

**Issue by akk01** [deweylab/CellO#5]
`(317/317)
Training classifier for label CL:0001044...
Number of positive items: 2
Number of negative items: 4032
done.
Writing trained model to test.model.dill
Found CellO resources at 'cello/resources'.
---------------------------------------------------------------------------
InvalidIndexError                         Traceback (most recent call last)
<ipython-input-12-b340cc4fa6fb> in <module>
      6     rsrc_loc=cello_resource_loc,
      7     out_prefix=model_prefix,
----> 8     log_dir=os.getcwd()
      9 )

~/.conda/envs/genomics/lib/python3.7/site-packages/cello/scanpy_cello.py in cello(adata, clust_key, rsrc_loc, algo, out_prefix, model_file, log_dir, term_ids, remove_anatomical_subterms)
    148         rsrc_loc=rsrc_loc,
    149         log_dir=log_dir,
--> 150         remove_anatomical_subterms=remove_anatomical_subterms
    151     )
    152 

~/.conda/envs/genomics/lib/python3.7/site-packages/cello/cello.py in predict(ad, mod, algo, clust_key, log_dir, remove_anatomical_subterms, rsrc_loc)
    235         algo=algo,
    236         clust_key=clust_key,
--> 237         log_dir=log_dir
    238     )
    239 

~/.conda/envs/genomics/lib/python3.7/site-packages/cello/cello.py in _raw_probabilities(ad, mod, algo, clust_key, log_dir)
    415     # Shuffle columns to be in accordance with model
    416     features = mod.classifier.features
--> 417     ad = ad[:,features]
    418 
    419     # Cluster

~/.conda/envs/genomics/lib/python3.7/site-packages/anndata/_core/anndata.py in __getitem__(self, index)
   1106     def __getitem__(self, index: Index) -> "AnnData":
   1107         """Returns a sliced view of the object."""
-> 1108         oidx, vidx = self._normalize_indices(index)
   1109         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1110 

~/.conda/envs/genomics/lib/python3.7/site-packages/anndata/_core/anndata.py in _normalize_indices(self, index)
   1087 
   1088     def _normalize_indices(self, index: Optional[Index]) -> Tuple[slice, slice]:
-> 1089         return _normalize_indices(index, self.obs_names, self.var_names)
   1090 
   1091     # TODO: this is not quite complete...

~/.conda/envs/genomics/lib/python3.7/site-packages/anndata/_core/index.py in _normalize_indices(index, names0, names1)
     34     ax0, ax1 = unpack_index(index)
     35     ax0 = _normalize_index(ax0, names0)
---> 36     ax1 = _normalize_index(ax1, names1)
     37     return ax0, ax1
     38 

~/.conda/envs/genomics/lib/python3.7/site-packages/anndata/_core/index.py in _normalize_index(indexer, index)
     96             return positions  # np.ndarray[int]
     97         else:  # indexer should be string array
---> 98             positions = index.get_indexer(indexer)
     99             if np.any(positions < 0):
    100                 not_found = indexer[positions < 0]

~/.conda/envs/genomics/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_indexer(self, target, method, limit, tolerance)
   3170         if not self.is_unique:
   3171             raise InvalidIndexError(
-> 3172                 "Reindexing only valid with uniquely valued Index objects"
   3173             )
   3174 

InvalidIndexError: Reindexing only valid with uniquely valued Index objects`

**Comment by mbernste** [comment]
Hi, 

I'm sorry you are experiencing this error. Would it be possible to point me to the dataset that you are using? 

Matt

**Comment by akk01** [comment]
Sure. I can share the data. Just wanted to make sure that if this is th right approach: 
` import scanpy as sc
adata = sc.read_10x_h5("sample/outs/filtered_feature_bc_matrix.h5")`

**Comment by mbernste** [comment]
I believe this issue is due to the fact that there are duplicate gene names/identifiers in the input data matrix.  You may try to run the following command before running CellO:

adata.adata.var_names_make_unique()

This will force all gene names to be unique.

In general, I will add a more informative error message to the next version of CellO that explains this issue.
