### ISSUE TITLE
resources are downloaded even if -f specified

### ISSUE THREAD

**Issue by Jon-bioinfo** [deweylab/CellO#6]
running cello_predict with -f 'path to folder which contains resources' i get the message 
```
Loading data from <>
Loaded data matrix with 4245 cells and 36601 genes.
Loading model from <>
Normalizing counts...
done.
Could not find the CellO resources directory called <cwd>
```

Looking at the code perhaps rsrc_loc is not being passed through to run_cello and cello.predict?

**Comment by mbernste** [comment]
Thanks for your interest in CellO; I'm sorry you are running into this issue. Do you mind posting the full command that you are running? I suspect the issue is with the structure of the command. It looks to me like the argument passed to the "-f" argument is the string "<cwd>".

**Comment by Jon-bioinfo** [comment]
Sorry I was clipping the paths out, by `<cwd>` i meant the current working directory. The command:
```
    cello_predict -d 10x \
                  -u COUNTS \
                  -s 3_PRIME \
                  -o annotation/cello/  \
                  -f /home/jonathan/resources/cello/ \
                  -m /home/jonathan/resources/cello/resources/trained_models/update.10x.dill  \
                  cellranger_output/
```

gives me
```
Loading data from cellranger_output/...
Loaded data matrix with 2255 cells and 36601 genes.
Loading model from /home/jonathan/resources/cello/resources/trained_models/update.10x.dill...
Normalizing counts...
done.

        Could not find the CellO resources directory called
        'resources' in '/home/jonathan/project/
```

when `/home/jonathan/resources/cello/` contains the resources folder
```
ls /home/jonathan/resources/cello/resources/
gene_metadata  README  trained_models  training_set
```

**Comment by mbernste** [comment]
I apologize for the delay in addressing this issue. Indeed, as you pointed out, the `rsrc_loc` variable was not being passed through `run_cello` and `cello.predict`. 

I have fixed this bug and updated the version of CellO in pip. Once you reinstall the code, it should work. Please let me know if you experience an issue!
