### ISSUE TITLE
PCA Error

### ISSUE THREAD

**Issue by mbcouger** [deweylab/CellO#7]
Hello Deweylab, 

 Hope the start of the summer is going well. When running CellO with scanpy with a larger single cell set (170k cells) I get the following error: 

Could not find compatible pre-trained model.
Found CellO resources at './resources'.
Loading ontology...
Loading expression data from ./resources/training_set/log_tpm.h5...
Loaded matrix of shape (4293, 58243)
done.
Inferred that input file uses HGNC gene symbols.
Of 2675 genes in the input file, 2508 were found in the training set of 58243 genes.
Training model...
Fitting PCA with 3000 components...

ValueError: n_components=3000 must be between 1 and min(n_samples, n_features)=2508 with svd_solver='randomized'

Is there a suggestion to reducing the size or some other method to fix this? 

I get these warnings prior to the error but I am unsure if these are causing it: 

/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator PCA from version 0.22.2.post1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.22.2.post1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(

Many Thanks!
Brian

**Comment by mbcouger** [comment]
I think I fixed this, it was an error on my part for using my filtered and not raw data. 

Many Thanks!
Brian

**Comment by mbernste** [comment]
Hi, I'm glad you found the issue! I'm also glad to hear CellO was able to scale to a dataset of that size. We have not tested it yet on data quite so large.

Let me know if you experience any other issues.

Best,
Matt

**Comment by mbcouger** [comment]
Hello Matt, 

 Thank you for the reply, I ran into another issue, so basically I have followed the scanpy protocol here for my datasets: https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html

I was able to train the model for CellO using the adata.raw however after the training I get the following error: 
"'Raw' object has no attribute 'obs'" This happens shortly after "Done. Writing trained model to xxx" I am assuming this happens because I do not have any Leiden clusters assigned with the raw portion. 

My question is there anyway to run this on my "adata" filtered final clusters but train it on the raw ones. I guess either through adding the raw data as a dimension or invoking CellO a certain way? Alternatively I could try running the protocol on non-filtered data then transferring the barcode over but that would be a lot of work and would ignore my efforts to normalize regress out MT counts and filter out batch effects.

Cheers,
Brian

**Comment by mbernste** [comment]
Hi Brian, 

If I understand your problem correctly, you wish to train CellO on the raw data, but then run CellO on filtered data?

Given that it sounds like you have at least trained a model on on your raw data, that model is saved to a file "xxx". You can then use this saved model and run it on a different dataset. To do so, you would invoke the command:

model_prefix = "GSM3516673_MSK_LX682_NORMAL"

```
cello.scanpy_cello(
    adata,                                           # <-- the AnnData object
    clust_key='leiden',                      # <-- name of the column in adata.obs containing the cluster assignments
    rsrc_loc=cello_resource_loc,    # <-- CellO resources location
    model_file='xxx'                         # <-- Filename of the trained model
)
```

Generally speaking, CellO does have functionality for ONLY training and saving a model (and not running the model); you can run the command `cell_train_model` (code is here: https://github.com/deweylab/CellO/blob/master/cello/cello_train_model.py ). Unfortunately this script is not well documented yet; I will have to add some more documentation. 

Hopefully this was at all helpful. Please let me know if I missed the mark.
